# Generated by Django 4.1 on 2023-11-10 07:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('ea3d2136-656a-4fe7-a027-3ae48791b1a1'), editable=False, unique=True),
        ),
    ]
