version: '3.3'

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    container_name: backend
    build: ../car_access/
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    restart: always
    depends_on:
      - db
    env_file:
      - ./.env

volumes:
  postgres_data:
