# Generated by Django 4.1 on 2023-11-09 12:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.UUID('f66fab3e-2f17-413b-b7dd-f744b569fa5a'), editable=False, unique=True)),
                ('brand', models.CharField(max_length=20, verbose_name='Марка')),
                ('model', models.CharField(max_length=20, verbose_name='Модель')),
                ('plate_number', models.CharField(max_length=9, unique=True, verbose_name='Модель')),
                ('owners_name', models.CharField(max_length=70, verbose_name='Модель')),
                ('created_at', models.DateTimeField(editable=False, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(verbose_name='Обновлен')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
                'ordering': ['updated_at'],
            },
        ),
    ]
