# Generated by Django 4.1 on 2023-11-10 07:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.UUID('875d9073-431d-42ce-a00b-d9af28083f47'), editable=False, unique=True)),
                ('brand', models.CharField(max_length=20, verbose_name='Марка')),
                ('model', models.CharField(max_length=20, verbose_name='Модель')),
                ('plate_number', models.CharField(max_length=9, unique=True, verbose_name='Гос номер')),
                ('owners_name', models.CharField(max_length=70, verbose_name='ФИО владельца')),
                ('created_at', models.DateTimeField(editable=False, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(verbose_name='Обновлен')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
                'ordering': ['updated_at'],
            },
        ),
        migrations.DeleteModel(
            name='Cars',
        ),
    ]
